-- 1. CREATE TABLESPACES (Simple - just one for data)
CREATE TABLESPACE irrigation_data
DATAFILE 'C:\oracle21c\oradata\ORCL\tue_27242_aime_irrigationMS_db\irrigation_data01.dbf'
SIZE 200M AUTOEXTEND ON NEXT 100M MAXSIZE 2G;

-- 2. CREATE TEMPORARY TABLESPACE
CREATE TEMPORARY TABLESPACE irrigation_temp
TEMPFILE 'C:\oracle21c\oradata\ORCL\tue_27242_aime_irrigationMS_db\irrigation_temp01.dbf'
SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE 500M;

-- 3. CREATE APPLICATION USER (for your project)
CREATE USER irrigation_app IDENTIFIED BY aime2024
DEFAULT TABLESPACE irrigation_data
TEMPORARY TABLESPACE irrigation_temp
QUOTA UNLIMITED ON irrigation_data;

-- 4. GRANT PRIVILEGES TO APPLICATION USER
GRANT CONNECT, RESOURCE TO irrigation_app;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, 
      CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO irrigation_app;

-- 5. CREATE READ-ONLY USER FOR REPORTING (Optional)
CREATE USER irrigation_ro IDENTIFIED BY readonly2024;
GRANT CREATE SESSION TO irrigation_ro;