-- ============================================
-- PHASE VII: PART 3 - SIMPLE TRIGGERS
-- File: 03_simple_triggers.sql
-- ============================================

-- TRIGGER 1: Prevent manual watering task creation on weekends
CREATE OR REPLACE TRIGGER trg_no_manual_watering_weekend
BEFORE INSERT ON watering_tasks
FOR EACH ROW
DECLARE
    v_restriction_check VARCHAR2(100);
    v_audit_id NUMBER;
BEGIN
    -- Check if this is a MANUAL task (not generated by system)
    -- We'll assume manual tasks have NULL or specific values in certain columns
    -- For simplicity, let's assume: 
    -- - Manual tasks: completed_by is NULL at insertion
    -- - Automated tasks: completed_by = -1 (system) at insertion
    
    IF :NEW.completed_by IS NULL OR :NEW.completed_by != -1 THEN
        -- This appears to be a manual task
        v_restriction_check := fn_is_manual_op_allowed('WATERING_TASK', SYSDATE);
        
        IF v_restriction_check != 'ALLOWED' THEN
            -- Log the violation
            v_audit_id := fn_log_restriction_violation(
                'WATERING_TASKS', 'INSERT', v_restriction_check, USER
            );
            
            -- Raise application error
            RAISE_APPLICATION_ERROR(-20010, 
                'MANUAL WATERING TASK RESTRICTION: ' || v_restriction_check ||
                ' (Audit ID: ' || v_audit_id || ')');
        END IF;
    END IF;
END trg_no_manual_watering_weekend;
/

-- TRIGGER 2: Prevent system configuration changes on holidays
-- System configuration tables: GARDEN_ZONES, CROP_TYPES, USERS
CREATE OR REPLACE TRIGGER trg_no_config_on_holidays_gz
BEFORE INSERT OR UPDATE OR DELETE ON garden_zones
DECLARE
    v_restriction_check VARCHAR2(100);
    v_audit_id NUMBER;
BEGIN
    v_restriction_check := fn_is_manual_op_allowed('SYSTEM_CONFIG', SYSDATE);
    
    IF v_restriction_check != 'ALLOWED' THEN
        -- Log the violation
        v_audit_id := fn_log_restriction_violation(
            'GARDEN_ZONES', 
            CASE 
                WHEN INSERTING THEN 'INSERT'
                WHEN UPDATING THEN 'UPDATE'
                WHEN DELETING THEN 'DELETE'
            END,
            v_restriction_check, USER
        );
        
        -- Raise application error
        RAISE_APPLICATION_ERROR(-20011, 
            'SYSTEM CONFIGURATION RESTRICTION: ' || v_restriction_check ||
            ' (Audit ID: ' || v_audit_id || ')');
    END IF;
END trg_no_config_on_holidays_gz;
/

-- Similar trigger for CROP_TYPES
CREATE OR REPLACE TRIGGER trg_no_config_on_holidays_ct
BEFORE INSERT OR UPDATE OR DELETE ON crop_types
DECLARE
    v_restriction_check VARCHAR2(100);
    v_audit_id NUMBER;
BEGIN
    v_restriction_check := fn_is_manual_op_allowed('SYSTEM_CONFIG', SYSDATE);
    
    IF v_restriction_check != 'ALLOWED' THEN
        v_audit_id := fn_log_restriction_violation(
            'CROP_TYPES', 
            CASE 
                WHEN INSERTING THEN 'INSERT'
                WHEN UPDATING THEN 'UPDATE'
                WHEN DELETING THEN 'DELETE'
            END,
            v_restriction_check, USER
        );
        
        RAISE_APPLICATION_ERROR(-20012, 
            'SYSTEM CONFIGURATION RESTRICTION: ' || v_restriction_check ||
            ' (Audit ID: ' || v_audit_id || ')');
    END IF;
END trg_no_config_on_holidays_ct;
/

-- Test the triggers
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== SIMPLE TRIGGER TESTS ===');
    
    -- Check current day
    IF fn_is_weekend(SYSDATE) = 'Y' THEN
        DBMS_OUTPUT.PUT_LINE('Today is weekend - manual watering should be blocked');
        
        -- Try to insert manual watering task (should fail)
        BEGIN
            INSERT INTO watering_tasks (task_id, zone_id, scheduled_date, task_status)
            VALUES (seq_task_id.NEXTVAL, 1, SYSDATE + 1, 'PENDING');
            DBMS_OUTPUT.PUT_LINE('ERROR: Manual watering allowed on weekend!');
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('SUCCESS: Manual watering blocked: ' || SQLERRM);
        END;
    ELSE
        DBMS_OUTPUT.PUT_LINE('Today is weekday - manual watering should be allowed');
        
        -- Try to insert manual watering task (should succeed)
        BEGIN
            INSERT INTO watering_tasks (task_id, zone_id, scheduled_date, task_status)
            VALUES (seq_task_id.NEXTVAL, 1, SYSDATE + 1, 'PENDING');
            DBMS_OUTPUT.PUT_LINE('SUCCESS: Manual watering allowed on weekday');
            ROLLBACK; -- Clean up
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
        END;
    END IF;
    
    -- Test automated task (should always work)
    DBMS_OUTPUT.PUT_LINE('Testing automated task insertion...');
    BEGIN
        INSERT INTO watering_tasks (task_id, zone_id, scheduled_date, task_status, completed_by)
        VALUES (seq_task_id.NEXTVAL, 1, SYSDATE + 1, 'PENDING', -1);
        DBMS_OUTPUT.PUT_LINE('SUCCESS: Automated task allowed');
        ROLLBACK;
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
    END;
    
END;
/